# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ce9bde7803c60c1ba88a546db9d7e2ac4863dea0812191d23675a9430a514016c9c5f71863e3aaa843ec14d0af2d516bdbde96523e784a6a930ddcb8f3c10e8d

test:
  secret_key_base: 3c7048f353843100731aaacf4a22341c879b67ee95df779507e93b1064e9bd2ba1d1e2cfde1732d25ec53a527668482d699f12b2db8f8f6cb5611417ad507531

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
